export enum OperationEvent {
  ADD,
  EDIT,
  MANANGE,
}

export enum REQUEST_STATUSES {
  ACCEPTED = "ACCEPTED",
  NOT_SENT = "NOT_SENT",
  REJECTED = "REJECTED",
  SENT = "SENT",
  PENDING = "PENDING",
  CONFIDENTIAL = "CONFIDENTIAL",
}
